dailyfresh/dailyfresh/urls.py
#coding=utf-8
"""dailyfresh URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('df_goods.urls')),# 主页/商品
    url(r'^user/', include('df_user.urls')),# 用户登陆/注册/用户中心
    url(r'^cart/', include('df_cart.urls')),# 购物车
    url(r'^myorder/',include('df_order.urls')),# 订单

    url(r'^tinymce/', include('tinymce.urls')),# 富文本编辑器
    url(r'^search/', include('haystack.urls')),# 搜索：第三方
]

dailyfresh/df_cart/urls.py
# coding=utf-8
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$',views.cart_list),
    url(r'^add(\d+)_(\d+)/?$',views.add),
    url(r'^get/?$',views.cart_count),
    url(r'^delete/?$',views.cart_delete),

]

dailyfresh/df_order/models.py
#coding=utf-8
from django.db import models

# Create your models here.
class OrderInfo(models.Model):# 主表
    oid= models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey('df_user.FreshInfo')#关联:一对多,生成表是user_id
    isPay = models.BooleanField(default=False)
    odate = models.DateTimeField(auto_now_add=True)
    ototal = models.DecimalField(max_digits=7,decimal_places=2)#这个订单总金额:5+2小数
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5,decimal_places=2)#单价
    count = models.IntegerField()

dailyfresh/templates/html/cart.html
{%extends 'base.html'%}
{%block head%}
<script>

    //函数写在function外面
    //表示的是windows下的
    //this
    //这里只能写函数!!

    // 删除
      function del(cart_id) {
         if (confirm('确定要删除吗?')){
            $.get('/cart/delete/?cart_id='+cart_id,function (data) {
            if(data.delete == "ok"){
                $('#'+cart_id).remove();//删除ul
                calculate()
                }
            });
        }
      }

        // 计算函数
     function calculate() {
         //统计个数
        count=$('.cart_list_td').length;
        $('.total_count em').text(count);//上部分:全部商品
        count2 = 0;
        //小计和总计
         t = 0;
         $('.cart_list_td .col06').each(function () {
             price = parseFloat($(this).siblings('.col05').text());
             //alert(price)
             num = $(this).find('.num_show').val();
             //alert(num)
             kucun = $(this).siblings('.col03').find('em').text();
             //alert(kucun);
{#            $(this).find('.num_gt').hidden();;#}
             if (num > kucun){
               $(this).find('.num_gt').html('大于库存').show();
             }else {
                 $(this).find('.num_gt').hide()
             }

             prices = num * price;
             $(this).siblings('.col07').text(prices.toFixed(2) + '元');
             if ($(this).siblings('.col01').children('input').prop('checked')){
                 t += prices;
                 count2 +=1;
             }
         });
         $('.settlements .col03 em').text(t.toFixed(2));
         $('.settlements .col03 b').text(count2);//下部分:共计商品
     }


  $(function () {
      calculate();
 {#----------------------------勾选:全选,全消---------------------------------#}

      //勾选:全选,全消
      $('#check_all').change(function () {
          //if($(this).prop('checked')){
        //    $(':checkbox').prop('checked',true);
        //}else{
        //    $(':checkbox').prop('checked',false);
        //}
          $(':checkbox:not(#check_all)').prop('checked',$(this).prop('checked'))
            calculate();
      });

        //选择
      $(':checkbox:not(#check_all)').change(function () {
          if($(':checkbox:not(#check_all)').length == $(':checked:not(#check_all)').length){
              $('#check_all').prop('checked',true);
          }
          else{
              $('#check_all').prop('checked',false);
          }
          calculate();
      });
{#----------------------------加减和手动改数量||第一种---------------------------------#}

{#    // 加#}
{#    $('.add').click(function () {#}
{#       var kucun = $(this).parents('.col06').siblings('.col03').find('em').text();#}
{#        var num_show = $(this).prev();#}
{#        var num = parseInt(num_show.val());#}
{#        num_show.val(num+1);#}
{#        if (num >= kucun){#}
{#            num_show.val(kucun);#}
{#        }#}
{#        calculate();#}
{##}
{#        cart_id = $(this).parents('.col06').find('#cart_id').text();#}
{#        count = $(this).parents('.col06').find('.num_show').val();#}
{#        $.get('/cart/get/?cart_id='+cart_id+'&count='+count);#}
{#    });#}
{#    // 减#}
{#     $('.minus').click(function () {#}
{#         var num_show = $(this).next();#}
{#        var num = parseInt(num_show.val());#}
{#        if (num > 1){#}
{#            num_show.val(num-1);#}
{#        }#}
{#        calculate();#}
{##}
{#        cart_id = $(this).parents('.col06').find('#cart_id').text();#}
{#        count = $(this).parents('.col06').find('.num_show').val();#}
{#        $.get('/cart/get/?cart_id='+cart_id+'&count='+count);#}
{#    });#}
{#    // 手动改数量#}
{#     $('.num_show').blur(function () {#}
{#         var kucun = $(this).parents('.col06').siblings('.col03').find('em').text();#}
{#         var num_show = $(this);#}
{#         var num = parseInt($(this).val());#}
{#         //去除小数点 或 数字+字母#}
{#         num_show.val(num);#}
{#        if (num <= 1 || isNaN(num)){#}
{#            num_show.val(1);#}
{#        }#}
{#        else  if (num >= kucun){#}
{#            num_show.val(kucun);#}
{#        }#}
{#       calculate();#}
{#         //直接获取input里面id={{ cart_id }}的值#}
{#         //cart_id=$(this).parents('.col06').prevAll('input').val();#}
{#     // prevAll  可以用表达式过滤====查找当前元素之前所有的同辈元素#}
{##}
{#        cart_id = $(this).parents('.col06').find('#cart_id').text();#}
{#        count = $(this).parents('.col06').find('.num_show').val();#}
{#        $.get('/cart/get/?cart_id='+cart_id+'&count='+count);#}
{#     });#}


{#----------------------------加减和手动改数量||第二种---------------------------------#}

      // 加
    $('.add').click(function () {
        var num = parseInt($(this).prev().val());
        num +=1;
        $(this).prev().val(num).blur();//!!!
    });
        // 减
     $('.minus').click(function () {
        var num = parseInt($(this).next().val());
        num -=1;
       $(this).next().val(num).blur()
    });

      // 手动改数量
     $('.num_show').blur(function () {
         var kucun = $(this).parents('.col06').siblings('.col03').find('em').text();
         var num = parseInt($(this).val());
         //去除小数点
         if (num <= 1 || isNaN(num)){
            num = 1;
        }
        if (num >= kucun){
            num = kucun;
        }

{#         //直接获取input里面id={{ cart_id }}的值#}
{#        // cart_id=$(this).parents('.col06').prevAll('input').val();#}
{#            //   prevAll  可以用表达式过滤====查找当前元素之前所有的同辈元素#}

         cart_id=$(this).parents('.col06').siblings('.col01').find('input').val();

         input_count = $(this);
        $.get('/cart/get/',{'cart_id':cart_id,'count':num},function (data) {
            input_count.val(data.count);
            calculate();
        });
        //calculate()  此处的代码比位置１处的代码先执行!  放这里会产生bug
     });

})

</script>
{%endblock head%}

{%block content%}

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="get" action="/myorder/">
    {% if carts %}
        {% for cart in carts %}
	<ul class="cart_list_td clearfix" id="{{ cart.id }}">
		<li class="col01"><input type="checkbox" name="cart_id" value='{{cart.id}}' checked></li>
        {#        form提交需要键值对:input===name,value必须要有值#}
		<li class="col02"><a href="/detail{{ cart.goods.id }}"><img src="/static/{{ cart.goods.gpic }}"></a></li>
		<li class="col03"> {{ cart.goods.gtitle }}
            <br><span style="color:red;font-weight: bold;">
                库存：<em>{{cart.goods.gkucun}}</em></span>
        </li>
		<li class="col04">{{cart.goods.gunit}}</li>
		<li class="col05">{{cart.goods.gprice}}</li>
		<li class="col06">
            <div id="cart_id" style="display: none" >{{ cart.id }}</div>
			<div class="num_add">
				<a href="javascript:;" class="minus fl">-</a>
				<input type="text" class="num_show fl" value="{{ cart.count }}">
				<a href="javascript:;" class="add fl">+</a>
            </div>
            <div class="num_gt" style="color: red;height: 30px;line-height: 30px;"></div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:del({{ cart.id }});">删除</a></li>
	</ul>
        {% endfor %}
   {% else %}
        <div class="total_count">没有商品</div>
   {% endif %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" id="check_all" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
</form>

{%endblock content%}

dailyfresh/templates/html/detail.html
{%extends 'list_detail.html' %}

{%block head%}
<script>

    // 乘法函数
     function mul() {
        num = parseInt($('.num_show').val());
        price = parseFloat($('#price').text());
        prices = num*price;

        $('#prices').text(prices.toFixed(2)+'元');
    }


$(function () {

{#----------------------------加减和手动改数量||第一种---------------------------------#}

{#    var kucun = parseInt($('#kucun').text());#}
{#    //alert(count);#}
{#    // 加#}
{#    $('.add').click(function () {#}
{#        num = parseInt($('.num_show').val());#}
{#        if (num < kucun){#}
{#             $('.num_show').val(kucun);#}
{#             $('.num_show').val(num+1);#}
{#        }#}
{#        mul();#}
{#    });#}
{#    // 减#}
{#     $('.minus').click(function () {#}
{#        num = parseInt($('.num_show').val());#}
{#        if (num > 1){#}
{#           $('.num_show').val(num-1);#}
{#        }#}
{#        mul();#}
{#    });#}
{#    // 手动改数量#}
{#     $('.num_show').blur(function () {#}
{#         num = parseInt($('.num_show').val());#}
{#         //去除小数点 或 数字+字母#}
{#         $('.num_show').val(num);#}
{#         // alert(num);#}
{#        if (num <= 1 || isNaN(num)){#}
{#            $('.num_show').val(1);#}
{#        }#}
{#        else  if (num >= kucun){#}
{#            $('.num_show').val(kucun);#}
{#        }#}
{#         mul();#}
{#     });#}

{#----------------------------加减和手动改数量||第二种---------------------------------#}

        //加
        $('.add').click(function () {
            num = parseInt($('.num_show').val());
            $('.num_show').val(num+1).blur();
        });
        //减
        $('.minus').click(function () {
            num = parseInt($('.num_show').val());
            $('.num_show').val(num-1).blur();
            });
        // 手动改数量
        $('.num_show').blur(function () {
            kucun = parseInt($('#kucun').text());
            num = parseInt($('.num_show').val());
            //去除小数点 或 数字+字母
            $('.num_show').val(num);
            if (num >= kucun){
                $('.num_show').val(kucun);
            }
            if (num <= 1 || isNaN(num)){
                $('.num_show').val(1);
            }
            mul();
        });

{#----------------------------加入购物车/动画---------------------------------#}

        //获取坐标
	    var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 加入购物车
		$('.add_cart').click(function(){

			$.get('/cart/add{{ goods.id }}_'+$('.num_show').val()+'/',function (data) {
                if (data.islogin == 0){
                    //ajax传过来data字典,判断是否登录,没登录就本地跳转到登录页面
                     location.href='/user/login.html/';
                    return;
                }else{
                    $('#show_count').html(data.count);
                }
                //动画
                $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
            .animate({'left': $to_y+7, 'top': $to_x+7},"fast", function() {
                $(".add_jump").fadeOut('fast');
            });
            })

			});

{#----------------------------立即购买---------------------------------#}

     // 立即购买
     $('.buy_btn').click(function () {
         //判断是否登录，若未登录则提示先登录
			if($('.login_btn').text().indexOf('登录')>=0){
			    alert('请先登录后再购买');
			    location.href='/user/login.html';
				return;
			}
            num = parseInt($('.num_show').val());
{#            $.get('/order/instantly/',{'goods_id':{{ goods.id }},'count':num},function (data) {#}
{#			    //转向订单页面#}
{#				location.href='/myorder/?cart_id='+data.cart_id;#}
{#            });#}
           $.get('/cart/add{{ goods.id }}_'+num+'/',function (data) {
			    //转向订单页面
				location.href='/myorder/?cart_id='+data.cart_id;
            });

    });
});

</script>
{%endblock head%}

        {%block detail_1%}

            <span>></span>
		<a href="#">商品详情</a>

        {%endblock detail_1%}


{%block detail_2%}

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ goods.gpic }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.gtitle }}</h3>
			<p>草莓浆果柔软多汁，味美爽口，适合速冻保鲜贮藏。草莓速冻后，可以保持原有的色、香、味，既便于贮藏，又便于外销。</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.gprice }}元</em></span>
				<span class="show_unit">单  位：{{ goods.gunit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div>
			</div>
            <br />
            <div >库存剩余:<em id="kucun">{{ goods.gkucun }}份</em></div>

			<div class="total">总价：<em id="prices">{{ goods.gprice }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" >立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

{%endblock detail_2%}

{%block goods_div%}

	<div class="main_wrap clearfix">
		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
                {{ goods.gcontent|safe }}
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
    {% endblock goods_div%}

</div>
{%block goods_js%}

    <div class="add_jump"></div>


{%endblock goods_js%}

dailyfresh/templates/html/index.html
{%extends 'base.html'%}
{%block head%}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{%endblock head%}

{%block content%}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="#">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="#">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            <li><a href="/list1_1_1/" class="fruit" target="_blank">新鲜水果</a></li>
            <li><a href="/list2_1_1/" class="seafood" target="_blank">海鲜水产</a></li>
            <li><a href="/list3_1_1/" class="meet" target="_blank">猪牛羊肉</a></li>
            <li><a href="/list4_1_1/" class="egg" target="_blank">禽类蛋品</a></li>
            <li><a href="/list5_1_1/" class="vegetables" target="_blank">新鲜蔬菜</a></li>
            <li><a href="/list6_1_1/" class="ice" target="_blank">速冻食品</a></li>

		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/img/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/img/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/img/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/img/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/img/adv01.jpg"></a>
			<a href="#"><img src="/static/img/adv02.jpg"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
            {%for g in t1_click%}
				<a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list1_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner01.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t1_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for g in t2_click%}
				<a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list2_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner02.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t2_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for g in t3_click%}
				<a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list3_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner03.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t3_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for g in t4_click%}
				<a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list4_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner04.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t4_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for g in t5_click%}
				<a href="/detail{{g.id}}">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list5_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner05.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t5_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for g in t6_click%}
				<a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a>
				{%endfor%}
			</div>
			<a href="/list6_1_1/" class="goods_more fr" target="_blank">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/img/banner06.jpg"></div>
			<ul class="goods_list fl">
				{%for g in t6_new%}
				<li>
					<h4><a href="/detail{{g.id}}/">{{g.gtitle|truncatechars:15 }}</a></h4>
					<a href="/detail{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					<div class="prize">¥ {{g.gprice}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>

{%endblock content%}

dailyfresh/templates/html/user_center_order.html
{%extends 'center.html'%}
{%block head%}
<script>

$(function () {
    $('.order_goods_list').each(function () {
    price = $(this).children('.col02').find('span').text();
{#    price = parseFloat($(this).children('.col02').find('span').text());#}
    //alert(price)
    count = parseInt($(this).children('.col03').text());
    prices = price*count;
        $(this).children('.col04').text(prices.toFixed(2)+ '元')

})

})

</script>
{%endblock head%}

{%block content_div%}

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
        {%if pages.count > 0%}
            {% for g in pages %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ g.odate }}</li>
					<li class="col02">订单号：{{ g.oid }}</li>
					<li class="col02 stress">
                        {% if g.isPay %}已支付
                        {% else %}末支付
                        {% endif %}
                    </li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for p in g.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ p.goods.gpic }}"></li>
									<li class="col02">{{ p.goods.gtitle }}<em><span>{{ p.goods.gprice }}</span>元/{{ p.goods.gunit }}</em></li>
									<li class="col03">{{ p.count }}</li>
									<li class="col04">25.8元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ g.ototal }}元</td>
                            {% if g.isPay %}
							<td width="15%">已付款</td>
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>

                            {% else %}
							<td width="15%"><a href="/user/order/pay{{ g.oid }}" class="oper_btn">去付款</a></td>
                        {% endif %}
						</tr>
					</tbody>
				</table>
            {% endfor %}

			<div class="pagenation">
                <a href="/user/order1/">首页</a>
                {%if pages.has_previous%}
				    <a href="/user/order{{ pages.number|add:-1 }}"><上一页</a>
                {% else %}
                    <a href="" class="active"><上一页</a>
                {% endif %}
                {% for index in pages.paginator.page_range %}
                    {%if index == pages.number%}
				<a href="#" class="active">{{index}}</a>
                        {% else %}
				<a href="/user/order_{{ index }}/">{{ index }}</a>
				    {% endif %}
                {% endfor %}

            {% if pages.has_next %}
				<a href="/user/order{{ pages.number|add:1 }}">下一页></a>
                {% else %}
                <a href="" class="active">下一页></a>
            {% endif %}
             <a href="/user/order{{ pages.paginator.num_pages }}/">末页</a>
			</div>
        {% else %}
            暂无订单信息
        {% endif %}

		</div>
    </div>


{%endblock content_div%}